PHEE-477 Create an orb that fetches the docker images and do helm upgrade

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -49,15 +49,22 @@ jobs:
       # Install Docker to build and push the image
       - setup_remote_docker:
           version: 20.10.14
-
       # Build the Docker image
       - run:
           name: Build Docker image
           command: |
+            #Check for PR title Validity
+            
+            PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+            PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/ph-ee-importer-rdbms/pulls/$PR_NUMBER" | jq -r '.title')
+            JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+            if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
+            
             IMAGE_TAG=$CIRCLE_TAG
             ./gradlew checkstyleMain
             ./gradlew clean bootJar
             docker build -t openmf/ph-ee-importer-rdbms:latest .
+            docker image tag openmf/ph-ee-importer-rdbms:latest openmf/ph-ee-importer-rdbms:$JIRA_STORY
 
       # Log in to DockerHub using environment variables
       - run:
@@ -67,7 +74,16 @@ jobs:
       # Push the Docker image to DockerHub
       - run:
           name: Push Docker image to DockerHub
-          command: docker push openmf/ph-ee-importer-rdbms:latest
+          command: |
+            if [ "$CIRCLE_BRANCH" = "master" ]; then
+              docker push openmf/ph-ee-importer-rdbms:latest
+            fi
+            if [ "$CIRCLE_BRANCH" != "master" ]; then
+              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/ph-ee-importer-rdbms/pulls/$PR_NUMBER" | jq -r '.title')
+              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1)
+              docker push openmf/ph-ee-importer-rdbms:${JIRA_STORY}
+            fi
 
 workflows:
   version: 2
