[G2PCCODV-50] include Gov-360, Gov-325 update (#92)
* include Gov-360 update

* include Gov-325 update

* update tenants config

* remove extra fields from transfer

* add bpmn config bulk_processor_account_lookup

* update variable name

* import phee-494 changes from master

* fix gov-325 additions

* fix deduplication issues

* update pipeline

* temp remove checkstyle command

* remove schema_name

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,7 +20,8 @@ jobs:
           name: Build and Push Docker tag Image
           command: |
             # Set environment variables
-            IMAGE_TAG=importer_rdbms_2
+            IMAGE_TAG=$CIRCLE_TAG
+            
             # Check if the Docker image with the same tag already exists in Docker Hub
             if curl -s -f -u "$DOCKERHUB_USERNAME":"$DOCKERHUB_PASSWORD" "https://hub.docker.com/v2/repositories/openmf/ph-ee-importer-rdbms/tags/$IMAGE_TAG" > /dev/null; then
               echo "Skipping the build and push as the tag $IMAGE_TAG already exists in Docker Hub."
@@ -50,9 +51,19 @@ jobs:
       - run:
           name: Build Docker image
           command: |
-            IMAGE_TAG=importer_rdbms_2
+            #Check for PR title Validity
+            
+            IMAGE_TAG=$CIRCLE_TAG
             ./gradlew clean bootJar
-            docker build -t openmf/ph-ee-importer-rdbms:importer_rdbms_2 .
+            docker build -t openmf/ph-ee-importer-rdbms:latest .
+
+            if [ "$CIRCLE_BRANCH" != "develop" ]; then
+              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
+              docker image tag openmf/$CIRCLE_PR_REPONAME:latest openmf/$CIRCLE_PR_REPONAME:$JIRA_STORY
+            fi
       # Log in to DockerHub using environment variables
       - run:
           name: Login to DockerHub
@@ -61,8 +72,16 @@ jobs:
       # Push the Docker image to DockerHub
       - run:
           name: Push Docker image to DockerHub
-          command: docker push openmf/ph-ee-importer-rdbms:importer_rdbms_2
-
+          command: |
+            if [ "$CIRCLE_BRANCH" = "develop" ]; then
+              docker push openmf/ph-ee-importer-rdbms:latest
+            fi
+            if [ "$CIRCLE_BRANCH" != "develop" ]; then
+              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+              docker push openmf/$CIRCLE_PR_REPONAME:${JIRA_STORY}
+            fi
 workflows:
   version: 2
   build-and-push:
